### ISSUE TITLE
NoSuchMethodError on exit when an invalid import is run and Ctrl-D is used

### ISSUE THREAD

**Issue by refi64** [BlackHC/dart_repl#3]
```
ryan@DevPC-LX ~ $ pub global run dart_repl
Observatory listening on http://127.0.0.1:53556/
1.23.0 (Fri Apr 21 10:05:24 2017) on "linux_x64"
Type `exit()` to quit.
>>> import 'bad:import';
Unhandled exception:
Could not import "bad:import" from "file:///tmp/dart_repl48zwAL/cell2.dart": Unknown scheme (bad) for bad:import
null
>>> Unhandled exception:
NoSuchMethodError: The getter 'isEmpty' was called on null.
Receiver: null
Tried calling: isEmpty
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      runRepl (package:dart_repl/src/kernel.dart:54)
<asynchronous suspension>
#3      dartRepl (package:dart_repl/dart_repl.dart:17)
<asynchronous suspension>
#4      main (file:///home/ryan/.pub-cache/hosted/pub.dartlang.org/dart_repl-0.11.1/bin/dart_repl.dart:27)
<asynchronous suspension>
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
ryan@DevPC-LX ~ $ 
```

(You can't see it here, but I'm using Ctrl-D to exit.)

**Comment by BlackHC** [comment]
I've merged the pull request. Thanks to @mcmahonjohn for the PR!

**Comment by refi64** [comment]
The PR was me. :O

**Comment by BlackHC** [comment]
Awww, sorry! Thanks for the PR @kirbyfan64 and sorry for misattribution!
